### ISSUE TITLE
About pages and flat pages need review

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-django#168]
Guys we have dropped the ball on this one. Please:

# Part 0

- [x] Please unpublish any content in the about page (and the link) in production until content is approved and tasks below are carried out.

# Part 1

- [x] Ensure that Charlotte and her designated team members have logins to staging
- [x] Ensure that Flatpages is set up on staging
- [x] Ensure that any content written in staging uses the same css rules, fonts etc. as the rest of the site so that it will look consistent.
- [x] Make a placeholder page for 'About' on staging
- [x] Place any draft content there 
- [x] Let @Charlotte-Morgan and team edit the flat pages content for about on staging until they are happy, provide any guidance needed about how they should go about doing edits

# Part 2

- [x] Ensure that Charlotte and her designated team members have logins to production
- [x] Ensure that Flatpages is set up on production
- [x] Ensure that any content written in production uses the same css rules, fonts etc. as the rest of the site so that it will look consistent (as tested first on staging).
- [x] Make a link and page for 'About' on production
- [ ] Place the finalized content there taken from staging
- [ ] Ensure that @Charlotte-Morgan and team have needed permissions to edit the flat pages content for about on production as needed.

We need to be more rigorous and communicative about how we deploy stuff to production - if you have completed some work requested in a ticket, ping @Charlotte-Morgan and the appropriate members of her team and let them review it. Once reviewed, deploy to production and let her team know that it is deployed and ready for general consumption. We should definitely not be pushing out any half finished content or features onto production.

Thanks for your support in this, please treat it as urgent.

Tim

**Comment by lucernae** [comment]
Well I guess we can checkmark all that from my point of view 😛.

Just to clarify things.

- Flatpages is setup on staging with tiny-mce since, probably June. I already told @ivanbusthomi that he can play with staging until he is content, then create the exact same flatpage on production. Basically, what you suggest. Ivan knows about this.
- To delete/unpublish the flatpages, we can just delete the model. It can be accessed through Django admin the same way we create the page.
- I sent the credentials to emails yesterday cc'ing @Charlotte-Morgan @ivanbusthomi @timlinux @gubuntu . The relative url for django admin also listed there.
- Yesterday I already deleted the previous about page, but it show up again as coming soon. Then I deleted it again this morning. But this is a user generated content, so everyone with user access can delete it really, no need to wait for me.
- The about page will show up if you provide /about/ url, with the given title of your choice
- Yes, please treat staging as draft content. Feel free to put anything, after you are content, put similar content to prod.

> Once reviewed, deploy to production and let her team know that it is deployed and ready for general consumption. We should definitely not be pushing out any half finished content or features onto production.

Yes, that's why I pushed the flatpages first in site visit, then with tiny-mce just recently to production, because at that time, it wasn't ready. And again, I'm not responsible with the content itself.

This issue is mostly discussed in inasafe/inasafe-realtime#70

**Comment by gubuntu** [comment]
@lucernae I've just pasted the content from the Google doc into the staging about page and it's not formatting correctly, probably because it's brought over markup from google docs. So we'd have to clear formatting and reformat in TinyMCE then?

**Comment by gubuntu** [comment]
now just waiting for @ivanbusthomi to update content on staging, will close https://github.com/inasafe/inasafe-realtime/issues/70 when there is approved content in production

**Comment by Charlotte-Morgan** [comment]
@lucernae - thanks for the update. I think it is helpful if you can update tickets as you do the work so that we can all track or find the information when we need.  I have been looking at #70 and really had no idea that this was ready for us to use. 
Regarding TinyMCE, I am still not clear how we use this - do you have some sample for how we should format things? (No I have not looked at it and will not be able to for a few weeks) or maybe a link we can refer to?

**Comment by gubuntu** [comment]
@Charlotte-Morgan can I close?

**Comment by lucernae** [comment]
For my dear @Charlotte-Morgan you can see the live demo at https://staging.realtime.inasafe.org/

Screenshot to highlight:
<img width="854" alt="screen shot 2017-09-20 at 18 16 34" src="https://user-images.githubusercontent.com/831865/30641091-faf01fb6-9e2f-11e7-85ba-abfa08badac3.png">

<img width="1094" alt="screen shot 2017-09-20 at 18 18 25" src="https://user-images.githubusercontent.com/831865/30641151-2b038cf6-9e30-11e7-88bf-b73990462f93.png">

To set it up like that, I will explain how this different field works:
- Title: The title of the menu, for example below the "About" menu, the title is "Earthquake"
- Url: Can be anything as long as it is unique.
- Group of FlatPage: The title of the Group menu, for example the title is About. If several FlatPage have the same Group, in the UI it will be put on the same Group menu
- Order of the Page: This is used to fine tune the order. For example you can set Earthquake to order =0 and then Flood to order=1, to make sure Earthquake menu is always shown on top of Flood menu.

This implementation is based on the chosen mockup:
![inasafe django about](https://user-images.githubusercontent.com/831865/30641387-0d3acba2-9e31-11e7-9ec1-4687007accb4.png)

If you like it, I will update the changes to realtime.inasafe.org

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - that looks great thank you.

**Comment by gubuntu** [comment]
done and deployed
